---
title: "HW7"
author: "tori rose (vrose9)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(glmnet)
library(tidyverse)
```

## R Questions

```{r}
# change this once assignment link is updated
address <- "https://raw.githubusercontent.com/vrose99/Assignment7temp/main/shhs.txt"
raw_data <- read.csv(address)

# linear regression
bmi_points = raw_data %>% select(bmi) %>%  data.matrix()
linear_Model1 = lm(log(rdi4p + 1)~bmi_points, data = raw_data)

# Report the coefficients and a scatterplot with the fitted line.
summary(linear_Model1)
# NEED TO REPORT THE COEFFICIENTS!!! from above model !!!!!!!!!!!!!!!!!!!!!!!!11
```
```{r}
# scatterplot:
ggplot(raw_data, aes(x=bmi_points, y=log(1+ as.numeric(rdi4p))))+
  geom_point(size=2, shape=18, color="blue", alpha=0.4) + 
  geom_smooth(method = 'lm',color = 'red') # not sure if any of the flagged NA things are of significant note

# need to predict for bmi of 30 (just math using number from above)
# predict(linear_Model1, 30) # not actually this but similar

# need to write little about mean and intercept of coefficients (can do this later)

```

```{r}
# Squared Error Loss !!!!! NOT SURE ABOUT THIS

# need to add penalty still
linear_Model2 = lm(log(rdi4p + 1)~as.numeric(bmi) + as.numeric(Waist) + as.numeric(age) + sex, raw_data)
summary(linear_Model2)

```

```{r}
# Lasso (L1) Penalty

x = raw_data %>% select(bmi, Waist, age, sex) %>%  data.matrix()
class(x) <- "numeric"

## look at a prediction and classification tasks
y = log(raw_data$rdi4p + 1)

# fit lasso -> comes from alpha = 1 i think
linear_Model3 = glmnet(x, y, alpha = 1)

# Attach a plot of the coefficients as the L1 sum of the parameters varies.
plot(linear_Model3) ### NOT SURE IF THIS IS RIGHT
```


```{r}
#Define sleep disordered breathing as having an rdi4p greater than 15. Use logistic regression to fit a model on having sleep disordered breathing using waist, age, sex and bmi as predictors. Report and interpet the BMI coefficient

y_new <- raw_data$rdi4p > 15
glm.fit <- glm(y_new~x, raw_data, family = binomial)
summary(glm.fit)

# REPORT AND INTERPRET COEFFICIENT
```















